minor, str.join() expects strings
With versions below minimum version, instead of raising
an informative error message the following traceback occurs:
TypeError: sequence item 0: expected string, int found

Change-Id: I5ac35935cd61786181e1c6372e752a1600cc2c2d